// Language proficiency questions for each supported language
export const languageQuestions = {
  english: [
    {
      id: "lang_1",
      text: "Choose the correct sentence:",
      options: [
        "I have been working here since five years.",
        "I have been working here for five years.",
        "I am working here since five years.",
        "I work here for five years.",
      ],
      correctAnswer: 1, // Index of correct answer (0-based)
    },
    {
      id: "lang_2",
      text: "Which sentence uses the correct conditional form?",
      options: [
        "If I would have known, I would have told you.",
        "If I had known, I would told you.",
        "If I had known, I would have told you.",
        "If I knew, I would have told you.",
      ],
      correctAnswer: 2,
    },
    {
      id: "lang_3",
      text: "Select the sentence with the correct use of articles:",
      options: [
        "She is best employee in the company.",
        "She is a best employee in company.",
        "She is the best employee in the company.",
        "She is best employee in a company.",
      ],
      correctAnswer: 2,
    },
    {
      id: "lang_4",
      text: "Which sentence contains a phrasal verb?",
      options: [
        "I will call you tomorrow morning.",
        "I need to look into this issue further.",
        "The customer service was excellent.",
        "This product has many features.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_5",
      text: "Choose the correct reported speech:",
      options: [
        "He said that he is coming tomorrow.",
        "He said that he was coming the next day.",
        "He said that he will come tomorrow.",
        "He said that he comes the next day.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_6",
      text: "Which sentence uses the passive voice correctly?",
      options: [
        "The issue was resolved by the technical team.",
        "The technical team was resolved the issue.",
        "The issue resolved by the technical team.",
        "The technical team were resolving the issue.",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_7",
      text: "Choose the sentence with correct subject-verb agreement:",
      options: [
        "The customer, along with his family members, were upset.",
        "The customer, along with his family members, was upset.",
        "The customer, along with his family members, are upset.",
        "The customer, along with his family members, have been upset.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_8",
      text: "Which sentence uses the correct preposition?",
      options: [
        "I'm interested on the new service plan.",
        "I'm interested with the new service plan.",
        "I'm interested for the new service plan.",
        "I'm interested in the new service plan.",
      ],
      correctAnswer: 3,
    },
    {
      id: "lang_9",
      text: "Select the sentence with the correct use of comparatives:",
      options: [
        "This plan is more cheaper than the previous one.",
        "This plan is cheapest than the previous one.",
        "This plan is cheaper than the previous one.",
        "This plan is the cheaper than the previous one.",
      ],
      correctAnswer: 2,
    },
    {
      id: "lang_10",
      text: "Which sentence contains a correct idiomatic expression?",
      options: [
        "We need to take care of this issue by the book.",
        "We need to take care of this issue by the rules.",
        "We need to take care of this issue by the instructions.",
        "We need to take care of this issue by the manual.",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_11",
      text: "Choose the word that means 'a place where you can borrow books':",
      options: ["Bookshop", "Library", "Museum", "School"],
      correctAnswer: 1,
    },
    {
      id: "lang_12",
      text: "What is the meaning of 'to postpone'?",
      options: [
        "To cancel completely",
        "To delay until later",
        "To finish quickly",
        "To start immediately",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_13",
      text: "Choose the synonym for 'enormous':",
      options: ["Tiny", "Average", "Huge", "Beautiful"],
      correctAnswer: 2,
    },
    {
      id: "lang_14",
      text: "What does 'transparent' mean?",
      options: [
        "Very colorful",
        "You can see through it",
        "Very heavy",
        "Completely solid",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_15",
      text: "Choose the word that means 'to make something better':",
      options: ["Improve", "Destroy", "Maintain", "Ignore"],
      correctAnswer: 0,
    },
    {
      id: "lang_16",
      text: "What is the meaning of 'ambiguous'?",
      options: [
        "Very clear",
        "Having only one meaning",
        "Open to multiple interpretations",
        "Completely wrong",
      ],
      correctAnswer: 2,
    },
    {
      id: "lang_17",
      text: "Choose the correct definition of 'meticulous':",
      options: [
        "Careless and sloppy",
        "Showing great attention to detail",
        "Very fast",
        "Extremely loud",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_18",
      text: "What does 'to scrutinize' mean?",
      options: [
        "To examine very carefully",
        "To hide completely",
        "To speak loudly",
        "To move quickly",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_19",
      text: "Choose the synonym for 'ubiquitous':",
      options: ["Rare", "Found everywhere", "Unique", "Colorful"],
      correctAnswer: 1,
    },
    {
      id: "lang_20",
      text: "What is the meaning of 'to extrapolate'?",
      options: [
        "To remove completely",
        "To extend known data to predict unknown values",
        "To simplify a complex idea",
        "To repeat exactly",
      ],
      correctAnswer: 1,
    },
  ],

  dutch: [
    {
      id: "lang_1",
      text: "Kies de juiste zin:",
      options: [
        "Ik woon in Nederland sinds vijf jaar.",
        "Ik woon in Nederland voor vijf jaar.",
        "Ik woon in Nederland vijf jaar geleden.",
        "Ik woon al vijf jaar in Nederland.",
      ],
      correctAnswer: 3,
    },
    {
      id: "lang_2",
      text: "Welke zin gebruikt de juiste werkwoordsvorm?",
      options: [
        "Ik heb gisteren naar de winkel gegaan.",
        "Ik ben gisteren naar de winkel gegaan.",
        "Ik ben gisteren naar de winkel gaan.",
        "Ik heb gisteren naar de winkel gaan.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_3",
      text: "Kies de juiste lidwoordvorm:",
      options: [
        "Het meisje heeft een rode fiets.",
        "De meisje heeft een rode fiets.",
        "Een meisje heeft de rode fiets.",
        "Het meisje heeft de rood fiets.",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_4",
      text: "Welke zin bevat een scheidbaar werkwoord?",
      options: [
        "Ik bel de klant morgen.",
        "Ik help de klant met zijn probleem.",
        "Ik bel de klant terug morgen.",
        "Ik los het probleem op voor de klant.",
      ],
      correctAnswer: 3,
    },
    {
      id: "lang_5",
      text: "Kies de juiste indirecte rede:",
      options: [
        "Hij zei dat hij morgen komt.",
        "Hij zei dat hij morgen zou komen.",
        "Hij zei dat hij morgen zal komen.",
        "Hij zei dat hij morgen kwam.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_6",
      text: "Welke zin gebruikt de lijdende vorm correct?",
      options: [
        "De klacht wordt door de manager behandeld.",
        "De klacht wordt behandeld door de manager.",
        "De klacht is door de manager behandelen.",
        "De klacht door de manager wordt behandeld.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_7",
      text: "Kies de zin met de juiste meervoudsvorm:",
      options: [
        "De kinderen spelen met de balles.",
        "De kinderen spelen met de ballen.",
        "De kinderen speelt met de ballen.",
        "De kind speelt met de ballen.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_8",
      text: "Welke zin gebruikt het juiste voorzetsel?",
      options: [
        "Ik ben geïnteresseerd aan het nieuwe abonnement.",
        "Ik ben geïnteresseerd met het nieuwe abonnement.",
        "Ik ben geïnteresseerd in het nieuwe abonnement.",
        "Ik ben geïnteresseerd voor het nieuwe abonnement.",
      ],
      correctAnswer: 2,
    },
    {
      id: "lang_9",
      text: "Kies de zin met de juiste vergelijkende trap:",
      options: [
        "Dit abonnement is meer goedkoper dan het vorige.",
        "Dit abonnement is goedkoper dan het vorige.",
        "Dit abonnement is goedkoopste dan het vorige.",
        "Dit abonnement is de goedkoper dan het vorige.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_10",
      text: "Welke zin bevat een correcte Nederlandse uitdrukking?",
      options: [
        "We moeten deze zaak met de hand aanpakken.",
        "We moeten deze zaak met de voet aanpakken.",
        "We moeten deze zaak met de vinger aanpakken.",
        "We moeten deze zaak met de handschoen aanpakken.",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_11",
      text: "Kies het woord dat 'een plaats waar je boeken kunt lenen' betekent:",
      options: ["Boekhandel", "Bibliotheek", "Museum", "School"],
      correctAnswer: 1,
    },
    {
      id: "lang_12",
      text: "Wat betekent 'uitstellen'?",
      options: [
        "Volledig annuleren",
        "Tot later vertragen",
        "Snel afronden",
        "Onmiddellijk beginnen",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_13",
      text: "Kies het synoniem voor 'enorm':",
      options: ["Klein", "Gemiddeld", "Gigantisch", "Mooi"],
      correctAnswer: 2,
    },
    {
      id: "lang_14",
      text: "Wat betekent 'doorzichtig'?",
      options: [
        "Zeer kleurrijk",
        "Je kunt erdoorheen kijken",
        "Zeer zwaar",
        "Volledig vast",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_15",
      text: "Kies het woord dat 'iets beter maken' betekent:",
      options: ["Verbeteren", "Vernietigen", "Handhaven", "Negeren"],
      correctAnswer: 0,
    },
    {
      id: "lang_16",
      text: "Wat is de betekenis van 'dubbelzinnig'?",
      options: [
        "Zeer duidelijk",
        "Met slechts één betekenis",
        "Voor meerdere interpretaties vatbaar",
        "Volledig verkeerd",
      ],
      correctAnswer: 2,
    },
    {
      id: "lang_17",
      text: "Kies de juiste definitie van 'nauwgezet':",
      options: [
        "Slordig en onzorgvuldig",
        "Met grote aandacht voor detail",
        "Zeer snel",
        "Extreem luid",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_18",
      text: "Wat betekent 'onderzoeken' in de zin van grondig bekijken?",
      options: [
        "Zeer zorgvuldig bestuderen",
        "Volledig verbergen",
        "Luid spreken",
        "Snel bewegen",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_19",
      text: "Kies het synoniem voor 'alomtegenwoordig':",
      options: ["Zeldzaam", "Overal te vinden", "Uniek", "Kleurrijk"],
      correctAnswer: 1,
    },
    {
      id: "lang_20",
      text: "Wat is de betekenis van 'extrapoleren'?",
      options: [
        "Volledig verwijderen",
        "Bekende gegevens uitbreiden om onbekende waarden te voorspellen",
        "Een complex idee vereenvoudigen",
        "Exact herhalen",
      ],
      correctAnswer: 1,
    },
  ],

  german: [
    {
      id: "lang_1",
      text: "Wählen Sie den richtigen Satz:",
      options: [
        "Ich wohne in Deutschland seit fünf Jahren.",
        "Ich wohne in Deutschland für fünf Jahre.",
        "Ich wohne in Deutschland vor fünf Jahren.",
        "Ich wohne in Deutschland fünf Jahre lang.",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_2",
      text: "Welcher Satz verwendet die richtige Verbform?",
      options: [
        "Ich habe gestern ins Kino gegangen.",
        "Ich bin gestern ins Kino gegangen.",
        "Ich habe gestern ins Kino gehen.",
        "Ich bin gestern ins Kino gehen.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_3",
      text: "Wählen Sie den Satz mit dem richtigen Artikel:",
      options: [
        "Das Mädchen hat ein rotes Fahrrad.",
        "Die Mädchen hat ein rotes Fahrrad.",
        "Der Mädchen hat ein rotes Fahrrad.",
        "Das Mädchen hat eine rotes Fahrrad.",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_4",
      text: "Welcher Satz enthält ein trennbares Verb?",
      options: [
        "Ich rufe den Kunden morgen.",
        "Ich helfe dem Kunden mit seinem Problem.",
        "Ich rufe den Kunden morgen an.",
        "Ich verstehe das Problem des Kunden.",
      ],
      correctAnswer: 2,
    },
    {
      id: "lang_5",
      text: "Wählen Sie die richtige indirekte Rede:",
      options: [
        "Er sagte, dass er morgen kommt.",
        "Er sagte, dass er morgen kommen würde.",
        "Er sagte, dass er morgen kommen wird.",
        "Er sagte, dass er morgen käme.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_6",
      text: "Welcher Satz verwendet das Passiv korrekt?",
      options: [
        "Die Beschwerde wird vom Manager bearbeitet.",
        "Die Beschwerde wird bearbeitet vom Manager.",
        "Die Beschwerde ist vom Manager bearbeiten.",
        "Die Beschwerde vom Manager wird bearbeitet.",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_7",
      text: "Wählen Sie den Satz mit der richtigen Pluralform:",
      options: [
        "Die Kinder spielen mit den Balles.",
        "Die Kinder spielen mit den Bällen.",
        "Die Kinder spielt mit den Bällen.",
        "Das Kind spielen mit den Bällen.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_8",
      text: "Welcher Satz verwendet die richtige Präposition?",
      options: [
        "Ich bin interessiert an dem neuen Abonnement.",
        "Ich bin interessiert mit dem neuen Abonnement.",
        "Ich bin interessiert in dem neuen Abonnement.",
        "Ich bin interessiert für dem neuen Abonnement.",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_9",
      text: "Wählen Sie den Satz mit dem richtigen Komparativ:",
      options: [
        "Dieses Abonnement ist mehr billiger als das vorherige.",
        "Dieses Abonnement ist billiger als das vorherige.",
        "Dieses Abonnement ist billigste als das vorherige.",
        "Dieses Abonnement ist das billiger als das vorherige.",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_10",
      text: "Welcher Satz enthält einen korrekten deutschen Ausdruck?",
      options: [
        "Wir müssen diese Sache mit dem Fuß anfassen.",
        "Wir müssen diese Sache mit der Hand anfassen.",
        "Wir müssen diese Sache mit Samthandschuhen anfassen.",
        "Wir müssen diese Sache mit dem Finger anfassen.",
      ],
      correctAnswer: 2,
    },
    {
      id: "lang_11",
      text: "Wählen Sie das Wort, das 'ein Ort, wo man Bücher ausleihen kann' bedeutet:",
      options: ["Buchhandlung", "Bibliothek", "Museum", "Schule"],
      correctAnswer: 1,
    },
    {
      id: "lang_12",
      text: "Was bedeutet 'verschieben'?",
      options: [
        "Vollständig absagen",
        "Auf später verlegen",
        "Schnell beenden",
        "Sofort beginnen",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_13",
      text: "Wählen Sie das Synonym für 'riesig':",
      options: ["Winzig", "Durchschnittlich", "Enorm", "Schön"],
      correctAnswer: 2,
    },
    {
      id: "lang_14",
      text: "Was bedeutet 'durchsichtig'?",
      options: [
        "Sehr bunt",
        "Man kann hindurchsehen",
        "Sehr schwer",
        "Völlig fest",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_15",
      text: "Wählen Sie das Wort, das 'etwas besser machen' bedeutet:",
      options: ["Verbessern", "Zerstören", "Beibehalten", "Ignorieren"],
      correctAnswer: 0,
    },
    {
      id: "lang_16",
      text: "Was ist die Bedeutung von 'mehrdeutig'?",
      options: [
        "Sehr klar",
        "Mit nur einer Bedeutung",
        "Für mehrere Interpretationen offen",
        "Völlig falsch",
      ],
      correctAnswer: 2,
    },
    {
      id: "lang_17",
      text: "Wählen Sie die richtige Definition von 'akribisch':",
      options: [
        "Nachlässig und schlampig",
        "Mit großer Aufmerksamkeit für Details",
        "Sehr schnell",
        "Extrem laut",
      ],
      correctAnswer: 1,
    },
    {
      id: "lang_18",
      text: "Was bedeutet 'prüfen' im Sinne von genau untersuchen?",
      options: [
        "Sehr sorgfältig untersuchen",
        "Vollständig verstecken",
        "Laut sprechen",
        "Sich schnell bewegen",
      ],
      correctAnswer: 0,
    },
    {
      id: "lang_19",
      text: "Wählen Sie das Synonym für 'allgegenwärtig':",
      options: ["Selten", "Überall zu finden", "Einzigartig", "Bunt"],
      correctAnswer: 1,
    },
    {
      id: "lang_20",
      text: "Was ist die Bedeutung von 'extrapolieren'?",
      options: [
        "Vollständig entfernen",
        "Bekannte Daten erweitern, um unbekannte Werte vorherzusagen",
        "Eine komplexe Idee vereinfachen",
        "Genau wiederholen",
      ],
      correctAnswer: 1,
    },
  ],
};
